# auto-compile with Compass and Sass
# compass output path set in config.rb
guard 'compass' do
  watch('^compile/(.*).s[ac]ss')
end

#watch these folders/files and reload browser when they are saved
#get the chrome plugin for livereload in the chrome web store
guard 'livereload' do
  watch(%r{static/+\.(php|html)}) #watch html prototyping template folder
  watch(%r{templates/+\.(php|html)}) #watch cms template folder
  watch(%r{css/.+\.css})
  watch(%r{js/.+\.js})
end

#use juicer to merge files referenced in js and create a minified js file
#juicer wiki https://github.com/cjohansen/juicer/wiki/Usage
guard 'process', :name => 'Minify Main JS', :command => 'juicer merge compile/js/main.js -o js/main.js --force -i -s' do
  watch(%r{compile/js/main\.js})
end
guard 'process', :name => 'Minify Foundation JS', :command => 'juicer merge compile/js/foundation.js -o js/foundation.js --force -i -s' do
  watch(%r{compile/js/foundation\.js})
end